# Generated by Django 2.2.15 on 2022-07-16 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0030_auto_20220714_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 10, 39, 49, 247230), verbose_name='End date of the event: '),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 10, 39, 49, 247209), verbose_name='Start Date of the event: '),
        ),
    ]
