# Generated by Django 2.2.15 on 2022-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0031_auto_20220716_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_endtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='End date of the event: '),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_starttime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start Date of the event: '),
        ),
    ]
