# Generated by Django 2.2.15 on 2022-08-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0034_takedebaitregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takedebaitregistration',
            name='member_1_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='takedebaitregistration',
            name='member_2_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='takedebaitregistration',
            name='member_3_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='takedebaitregistration',
            name='member_4_name',
            field=models.CharField(max_length=150),
        ),
    ]
