# Generated by Django 2.2.15 on 2022-08-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0035_auto_20220825_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takedebaitregistration',
            old_name='primary_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='takedebaitregistration',
            name='team_name',
            field=models.CharField(default='team name', max_length=150),
            preserve_default=False,
        ),
    ]
