# Generated by Django 2.2.15 on 2022-09-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0036_auto_20220825_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takedebaitregistration',
            name='member_1_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='takedebaitregistration',
            name='member_2_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='takedebaitregistration',
            name='member_3_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='takedebaitregistration',
            name='member_4_number',
            field=models.CharField(max_length=15),
        ),
    ]
