# Generated by Django 2.2.15 on 2022-11-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0037_auto_20220901_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimalistPosterRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('destination', models.URLField()),
            ],
        ),
    ]
